name: Deploy Survey App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rep
        uses: actions/checkout@v4

      - name: forsitet2
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Сборка и пуш Docker-образа
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/survey-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/survey-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Подключение к серверу и деплой
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop survey_app || true
            docker rm survey_app || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/survey-app:latest
            docker run -d --name survey_app -p 8080:8080 --env-file .env ${{ secrets.DOCKER_USERNAME }}/survey-app:latest
